name: Remove Distribution Page of DeployGate.

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  deploygate:
    name: Remove Distribution Page of DeployGate.
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.after }}
      - uses: actions/github-script@v6
        id: get_distribution_key
        with:
          result-encoding: string
          script: |
            result = await github.rest.issues.listComments({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            var distribution_key = null;
            for (const comment of result.data.reverse()) {
              const found = comment.body.match(/https:\/\/deploygate.com\/distributions\/([a-f0-9]{40})/);
              if (found) {
                distribution_key = found[1];
                break;
              }
            }
            return distribution_key;
      - uses: jaxxstorm/action-install-gh-release@f2bcf7617d36fea65f0a9d261d4947b19947956e # v1.9.0
        with:
          repo: suzuki-shunsuke/github-comment
          tag: v6.0.0
          cache: enable
      - run: |
          github-comment hide
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - run: |
          curl -f -H "Authorization: Bearer ${{ secrets.DEPLOYGATE_USER_API_TOKEN }}" -X DELETE "https://deploygate.com/api/distributions/${{ steps.get_distribution_key.outputs.result }}"
        if: steps.get_distribution_key.outputs.result != 'null'
